// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeOpPmRFfEy40tzSD2Q5bpRTkpLNuldi8',
    appId: '1:560811182746:web:d940cc964622bb78956d23',
    messagingSenderId: '560811182746',
    projectId: 'pfef-46142',
    authDomain: 'pfef-46142.firebaseapp.com',
    storageBucket: 'pfef-46142.appspot.com',
    measurementId: 'G-GCZ1EHV8D4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl6Z-VpvZSw47fuvamWY7eEVGYujvSkS4',
    appId: '1:560811182746:android:9a8c7ecfa4441453956d23',
    messagingSenderId: '560811182746',
    projectId: 'pfef-46142',
    storageBucket: 'pfef-46142.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAdRYUBlUfdl8IKV9FJeAIHP1-JWL-ok8',
    appId: '1:560811182746:ios:71b7eaa11687d519956d23',
    messagingSenderId: '560811182746',
    projectId: 'pfef-46142',
    storageBucket: 'pfef-46142.appspot.com',
    androidClientId: '560811182746-r5t05gji8576e0ij2ogcotn1mglocq2m.apps.googleusercontent.com',
    iosClientId: '560811182746-pi21rn0gqu3h7kf3k9f8mhjrqpa215vf.apps.googleusercontent.com',
    iosBundleId: 'com.example.pfef',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAdRYUBlUfdl8IKV9FJeAIHP1-JWL-ok8',
    appId: '1:560811182746:ios:71b7eaa11687d519956d23',
    messagingSenderId: '560811182746',
    projectId: 'pfef-46142',
    storageBucket: 'pfef-46142.appspot.com',
    androidClientId: '560811182746-r5t05gji8576e0ij2ogcotn1mglocq2m.apps.googleusercontent.com',
    iosClientId: '560811182746-pi21rn0gqu3h7kf3k9f8mhjrqpa215vf.apps.googleusercontent.com',
    iosBundleId: 'com.example.pfef',
  );
}
